"""
Builds data/sample-data.json from an Excel export (same compact format that the Apps Script returns).
Customer PII (names, e-mails, phones, addresses, order/account numbers ...) is NEVER copied.

Usage:  python scripts/build_sample.py path/to/data_for_Dash.xlsx
"""
import sys, json, re, datetime as dt
import pandas as pd

src = sys.argv[1] if len(sys.argv) > 1 else "data_for_Dash.xlsx"
EPOCH = dt.date(1970, 1, 1)

def day_num(v):
    if pd.isna(v): return None
    if isinstance(v, str):
        v = pd.to_datetime(v, errors="coerce")
        if pd.isna(v): return None
    return (v.date() - EPOCH).days

def dur(t):
    if t is None or (isinstance(t, float) and pd.isna(t)): return 0
    if isinstance(t, dt.time): return t.hour * 3600 + t.minute * 60 + t.second
    return 0

def hour_of(v):
    """Best-effort hour (0-23) out of a time-ish cell — handles datetime.time,
    datetime.datetime, '14:32', '2:32 PM', or a bare leading '14'. Returns
    -1 if nothing usable is found (row is then skipped from hourly buckets,
    same as the Calls sheet already does for an unparsable Time Frame)."""
    if v is None or (isinstance(v, float) and pd.isna(v)): return -1
    if isinstance(v, dt.datetime): return v.hour
    if isinstance(v, dt.time): return v.hour
    s = str(v).strip()
    m = re.match(r"^(\d{1,2})", s)
    if not m: return -1
    h = int(m.group(1))
    low = s.lower()
    if "pm" in low and h != 12: h += 12
    if "am" in low and h == 12: h = 0
    return h if 0 <= h <= 23 else -1

# ---------- CALLS ----------
c = pd.read_excel(src, sheet_name="Calls Data")
dq, da, dr = {}, {}, {}
def enc(d, v):
    v = "" if pd.isna(v) else str(v).strip()
    if v not in d: d[v] = len(d)
    return d[v]

rows = []
for r in c.itertuples(index=False):
    d = day_num(r[1])
    if d is None: continue
    m = re.match(r"\s*(\d+)", str(r[2]))
    hour = int(m.group(1)) if m else -1
    agent = "" if pd.isna(r[7]) else str(r[7]).strip()
    rows.append([
        d, hour, enc(dq, r[0]), enc(da, agent) if agent else -1, enc(dr, r[12]),
        dur(r[13]), dur(r[17]), dur(r[18]), dur(r[19]), int(r[15]) if not pd.isna(r[15]) else 0,
    ])
calls = {
    "cols": ["d", "h", "q", "a", "r", "w", "t", "hd", "wu", "b"],
    "dict": {"queue": list(dq), "agent": list(da), "result": list(dr)},
    "rows": rows,
}

# ---------- SALES (non-PII columns only) ----------
s = pd.read_excel(src, sheet_name="sales Data")
MAP = {
    "campaign": "gRPCampaign Number", "agent": "Agent Name", "closer": "Closer Name", "team": "Team",
    "provider": "Provider", "services": "Services", "install": "Installation Type",
    "saleType": "Sales Call/Non Sales Call", "currentProvider": "Current Provider", "state": "State",
    "eero": "Eero Secure (Add On)", "acc": "ACC Account", "streaming": "Any Third Party Streaming Services Sold",
    "lead": "Lead Generated by (If Any)", "processed": "Sale Processed",
}
canc = [x for x in s.columns if x.startswith("Previous Services Cancelled")][0]
pt_cols = [x for x in s.columns if re.search(r"(points|ponts)$", x, re.I) and x.lower() != "total points"]
def clean(v):
    return None if pd.isna(v) else str(v).strip()

# Sale hour, for the Daily x Hourly matrix's "Sales" row — auto-detects a
# time-ish column on the sales sheet (skips the "Date" column itself).
# If your sheet's column isn't picked up correctly, hardcode it here, e.g.:
#   sale_time_col = "Time Frame"
_time_candidates = [c for c in s.columns if re.search(r"time|hour", c, re.I) and "date" not in c.lower()]
sale_time_col = _time_candidates[0] if _time_candidates else None
if sale_time_col:
    print(f"Sales hour column detected: '{sale_time_col}' (used for the hourly Sales row)")
else:
    print("No time/hour column found on 'sales Data' — the Sales row of the Daily x Hourly "
          "table will stay empty until one is added (see sale_time_col in this script).")

sales = []
for _, r in s.iterrows():
    d = day_num(r["Date"])
    if d is None: continue
    o = {"d": d, "h": hour_of(r[sale_time_col]) if sale_time_col else -1}
    for k, col in MAP.items(): o[k] = clean(r[col])
    o["cancelled"] = clean(r[canc])
    o["rgu"] = int(r["RGU's"]) if not pd.isna(r["RGU's"]) else 1
    pts = {re.sub(r"\s*(points|ponts)$", "", c_, flags=re.I).strip(): float(r[c_]) for c_ in pt_cols if not pd.isna(r[c_]) and float(r[c_]) != 0}
    o["pts"] = pts
    o["total"] = float(r["Total Points"]) if not pd.isna(r["Total Points"]) else sum(pts.values())
    sales.append(o)

out = {
    "ok": True, "source": "sample", "generatedAt": dt.datetime.now(dt.timezone.utc).isoformat(),
    "calls": calls, "sales": {"rows": sales},
    "meta": {"callRows": len(rows), "salesRows": len(sales)},
}
with open("data/sample-data.json", "w") as f:
    json.dump(out, f, separators=(",", ":"))
print("calls", len(rows), "sales", len(sales))
